<a href="https://colab.research.google.com/github/hetpatel1812/MachineLearning-Track/blob/main/Day_15/DeepLearning_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [3]:
df = pd.DataFrame({
    'soil_moiture' : [0.10,0.15,0.20,0.25,0.40,0.60,0.35,0.18,
                      0.45,0.05,0.80,0.27,0.55,0.70,0.12,0.30],
    'temprature_c' : [20,21,22,23,24,25,26,27,28,29,
                      30,31,32,33,34,35],
    'sunlight_hours' : [5,6,7,8,9,10,11,12,13,14,
                       15,16,17,18,19,20],
    'needs_water' : [0,0,0,0,1,1,1,1,1,1,
                     1,0,0,1,1,0]

})

In [4]:
df

    soil_moiture  temprature_c  sunlight_hours  needs_water
0           0.10            20               5            0
1           0.15            21               6            0
2           0.20            22               7            0
3           0.25            23               8            0
4           0.40            24               9            1
5           0.60            25              10            1
6           0.35            26              11            1
7           0.18            27              12            1
8           0.45            28              13            1
9           0.05            29              14            1
10          0.80            30              15            1
11          0.27            31              16            0
12          0.55            32              17            0
13          0.70            33              18            1
14          0.12            34              19            1
15          0.30            35              20            0

In [5]:
X = df[['soil_moiture','temprature_c','sunlight_hours']]
y = df['needs_water']

In [6]:
X_min= X.min()
X_max = X.max()
X_Scaled = (X-X_min)/(X_max-X_min + 1e-8)
X_Scaled

    soil_moiture  temprature_c  sunlight_hours
0       0.066667      0.000000        0.000000
1       0.133333      0.066667        0.066667
2       0.200000      0.133333        0.133333
3       0.266667      0.200000        0.200000
4       0.466667      0.266667        0.266667
5       0.733333      0.333333        0.333333
6       0.400000      0.400000        0.400000
7       0.173333      0.466667        0.466667
8       0.533333      0.533333        0.533333
9       0.000000      0.600000        0.600000
10      1.000000      0.666667        0.666667
11      0.293333      0.733333        0.733333
12      0.666667      0.800000        0.800000
13      0.866667      0.866667        0.866667
14      0.093333      0.933333        0.933333
15      0.333333      1.000000        1.000000

In [7]:
X_train,X_test,y_train,y_test = train_test_split(X_Scaled,y,test_size=0.25
                                                ,random_state = 42)

In [8]:
X_train

    soil_moiture  temprature_c  sunlight_hours
13      0.866667      0.866667        0.866667
11      0.293333      0.733333        0.733333
8       0.533333      0.533333        0.533333
9       0.000000      0.600000        0.600000
2       0.200000      0.133333        0.133333
15      0.333333      1.000000        1.000000
4       0.466667      0.266667        0.266667
7       0.173333      0.466667        0.466667
10      1.000000      0.666667        0.666667
12      0.666667      0.800000        0.800000
3       0.266667      0.200000        0.200000
6       0.400000      0.400000        0.400000

In [9]:
model = keras.Sequential([
    layers.Input(shape= (X_train.shape[1],)),
    layers.Dense(8,activation='relu'),
    layers.Dense(1,activation='sigmoid')
])

In [10]:
model.compile(optimizer='sgd' , loss='binary_crossentropy',metrics=['accuracy'])

In [11]:
History = model.fit(
    X_train,y_train,
    epochs=100,
    validation_split=0.2,
    batch_size=4,
    verbose= 1
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 117ms/step - accuracy: 0.3333 - loss: 0.7124 - val_accuracy: 0.6667 - val_loss: 0.6714
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.3333 - loss: 0.7032 - val_accuracy: 0.6667 - val_loss: 0.6722
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.3333 - loss: 0.7012 - val_accuracy: 0.3333 - val_loss: 0.6776
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.4444 - loss: 0.6936 - val_accuracy: 0.3333 - val_loss: 0.6823
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.4444 - loss: 0.6879 - val_accuracy: 0.3333 - val_loss: 0.6834
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.4444 - loss: 0.6866 - val_accuracy: 0.6667 - val_loss: 0.6845
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.4444 - loss: 0.6848 - val_accuracy: 0.6667 - val_loss: 0.6889
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5556 - loss: 0.6798 - val_accuracy: 0.6667 - val_loss: 0.6936
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6667 - loss: 0.6747 - val_accuracy: 0.6667 - val_loss: 0.6981
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6667 - loss: 0.6702 - val_accuracy: 0.3333 - val_loss: 0.7031
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.6661 - val_accuracy: 0.3333 - val_loss: 0.7031
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6667 - loss: 0.6665 - val_accuracy: 0.3333 - val_loss: 0.7038
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.6650 - val_accuracy: 0.3333 - val_loss: 0.7046
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6667 - loss: 0.6643 - val_accuracy: 0.3333 - val_loss: 0.7053
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6667 - loss: 0.6650 - val_accuracy: 0.3333 - val_loss: 0.7050
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.6639 - val_accuracy: 0.3333 - val_loss: 0.7050
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.6633 - val_accuracy: 0.3333 - val_loss: 0.7104
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.7778 - loss: 0.6601 - val_accuracy: 0.3333 - val_loss: 0.7100
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.6667 - loss: 0.6605 - val_accuracy: 0.3333 - val_loss: 0.7154
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.7778 - loss: 0.6556 - val_accuracy: 0.3333 - val_loss: 0.7151
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.7778 - loss: 0.6544 - val_accuracy: 0.3333 - val_loss: 0.7203
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.7778 - loss: 0.6507 - val_accuracy: 0.3333 - val_loss: 0.7252
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.7778 - loss: 0.6473 - val_accuracy: 0.3333 - val_loss: 0.7304
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.6667 - loss: 0.6440 - val_accuracy: 0.3333 - val_loss: 0.7354
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6667 - loss: 0.6412 - val_accuracy: 0.3333 - val_loss: 0.7406
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6667 - loss: 0.6381 - val_accuracy: 0.3333 - val_loss: 0.7459
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.5556 - loss: 0.6352 - val_accuracy: 0.3333 - val_loss: 0.7508
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.6667 - loss: 0.6341 - val_accuracy: 0.3333 - val_loss: 0.7494
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.6667 - loss: 0.6333 - val_accuracy: 0.3333 - val_loss: 0.7551
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.6667 - loss: 0.6310 - val_accuracy: 0.3333 - val_loss: 0.7602
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.6285 - val_accuracy: 0.3333 - val_loss: 0.7646
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.6283 - val_accuracy: 0.3333 - val_loss: 0.7698
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6667 - loss: 0.6245 - val_accuracy: 0.3333 - val_loss: 0.7690
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6667 - loss: 0.6247 - val_accuracy: 0.3333 - val_loss: 0.7683
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6667 - loss: 0.6248 - val_accuracy: 0.3333 - val_loss: 0.7731
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6667 - loss: 0.6232 - val_accuracy: 0.3333 - val_loss: 0.7722
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6667 - loss: 0.6244 - val_accuracy: 0.3333 - val_loss: 0.7697
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6667 - loss: 0.6240 - val_accuracy: 0.3333 - val_loss: 0.7753
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.6219 - val_accuracy: 0.3333 - val_loss: 0.7801
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.6667 - loss: 0.6200 - val_accuracy: 0.3333 - val_loss: 0.7850
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6667 - loss: 0.6185 - val_accuracy: 0.3333 - val_loss: 0.7898
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.6170 - val_accuracy: 0.3333 - val_loss: 0.7947
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6667 - loss: 0.6160 - val_accuracy: 0.3333 - val_loss: 0.7988
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.6146 - val_accuracy: 0.3333 - val_loss: 0.8041
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6667 - loss: 0.6133 - val_accuracy: 0.3333 - val_loss: 0.8086
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.6122 - val_accuracy: 0.3333 - val_loss: 0.8131
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6667 - loss: 0.6111 - val_accuracy: 0.3333 - val_loss: 0.8170
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6667 - loss: 0.6107 - val_accuracy: 0.3333 - val_loss: 0.8217
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6667 - loss: 0.6095 - val_accuracy: 0.3333 - val_loss: 0.8263
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6667 - loss: 0.6087 - val_accuracy: 0.3333 - val_loss: 0.8308
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6667 - loss: 0.6094 - val_accuracy: 0.3333 - val_loss: 0.8283
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6667 - loss: 0.6084 - val_accuracy: 0.3333 - val_loss: 0.8326
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6667 - loss: 0.6080 - val_accuracy: 0.3333 - val_loss: 0.8368
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6667 - loss: 0.6069 - val_accuracy: 0.3333 - val_loss: 0.8405
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6667 - loss: 0.6064 - val_accuracy: 0.3333 - val_loss: 0.8447
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.6060 - val_accuracy: 0.3333 - val_loss: 0.8400
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.6061 - val_accuracy: 0.3333 - val_loss: 0.8441
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6667 - loss: 0.6056 - val_accuracy: 0.3333 - val_loss: 0.8412
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6667 - loss: 0.6060 - val_accuracy: 0.3333 - val_loss: 0.8459
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.6667 - loss: 0.6071 - val_accuracy: 0.3333 - val_loss: 0.8503
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.6048 - val_accuracy: 0.3333 - val_loss: 0.8542
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6667 - loss: 0.6055 - val_accuracy: 0.3333 - val_loss: 0.8510
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6667 - loss: 0.6050 - val_accuracy: 0.3333 - val_loss: 0.8452
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.6053 - val_accuracy: 0.3333 - val_loss: 0.8397
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6667 - loss: 0.6057 - val_accuracy: 0.3333 - val_loss: 0.8440
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.6051 - val_accuracy: 0.3333 - val_loss: 0.8386
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.6054 - val_accuracy: 0.3333 - val_loss: 0.8342
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.6667 - loss: 0.6066 - val_accuracy: 0.3333 - val_loss: 0.8300
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.6667 - loss: 0.6061 - val_accuracy: 0.3333 - val_loss: 0.8275
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6667 - loss: 0.6064 - val_accuracy: 0.3333 - val_loss: 0.8322
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.6056 - val_accuracy: 0.3333 - val_loss: 0.8360
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6667 - loss: 0.6068 - val_accuracy: 0.3333 - val_loss: 0.8403
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6667 - loss: 0.6043 - val_accuracy: 0.3333 - val_loss: 0.8446
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.6039 - val_accuracy: 0.3333 - val_loss: 0.8490
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6667 - loss: 0.6033 - val_accuracy: 0.3333 - val_loss: 0.8535
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6667 - loss: 0.6028 - val_accuracy: 0.3333 - val_loss: 0.8575
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6667 - loss: 0.6028 - val_accuracy: 0.3333 - val_loss: 0.8616
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.6030 - val_accuracy: 0.3333 - val_loss: 0.8562
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.6667 - loss: 0.6023 - val_accuracy: 0.3333 - val_loss: 0.8606
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6667 - loss: 0.6022 - val_accuracy: 0.3333 - val_loss: 0.8553
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6667 - loss: 0.6024 - val_accuracy: 0.3333 - val_loss: 0.8593
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6667 - loss: 0.6017 - val_accuracy: 0.3333 - val_loss: 0.8560
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6667 - loss: 0.6037 - val_accuracy: 0.3333 - val_loss: 0.8600
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.6025 - val_accuracy: 0.3333 - val_loss: 0.8539
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6667 - loss: 0.6017 - val_accuracy: 0.3333 - val_loss: 0.8580
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.6032 - val_accuracy: 0.3333 - val_loss: 0.8619
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6667 - loss: 0.6017 - val_accuracy: 0.3333 - val_loss: 0.8558
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6667 - loss: 0.6013 - val_accuracy: 0.3333 - val_loss: 0.8499
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.6018 - val_accuracy: 0.3333 - val_loss: 0.8545
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6667 - loss: 0.6023 - val_accuracy: 0.3333 - val_loss: 0.8512
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6667 - loss: 0.6012 - val_accuracy: 0.3333 - val_loss: 0.8557
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6667 - loss: 0.6008 - val_accuracy: 0.3333 - val_loss: 0.8603
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6667 - loss: 0.6015 - val_accuracy: 0.3333 - val_loss: 0.8549
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6667 - loss: 0.6008 - val_accuracy: 0.3333 - val_loss: 0.8594
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6667 - loss: 0.6013 - val_accuracy: 0.3333 - val_loss: 0.8560
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6667 - loss: 0.6024 - val_accuracy: 0.3333 - val_loss: 0.8604
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6667 - loss: 0.6001 - val_accuracy: 0.3333 - val_loss: 0.8644
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6667 - loss: 0.5997 - val_accuracy: 0.3333 - val_loss: 0.8679
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.6667 - loss: 0.5996 - val_accuracy: 0.3333 - val_loss: 0.8622
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.5998 - val_accuracy: 0.3333 - val_loss: 0.8667